//! Guard for the subsetted Tabler icon font (#911).
//!
//! The shipped `tabler-icons.{woff2,min.css}` carry only the glyphs the
//! app uses, regenerated by `scripts/subset-tabler-icons.py` from the
//! in-tree `tabler-icons-full.*` source. This test fails if a template or
//! Rust handler references a real Tabler icon that isn't in the shipped
//! subset — i.e. someone added an icon but didn't re-run the script, which
//! would render a blank glyph in production.

use regex::Regex;
use std::collections::HashSet;
use std::fs;
use std::path::Path;

fn read_recursive(dir: &Path, ext: &str, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read_dir") {
        let p = entry.expect("dir entry").path();
        if p.is_dir() {
            read_recursive(&p, ext, out);
        } else if p.extension().and_then(|s| s.to_str()) == Some(ext) {
            out.push(fs::read_to_string(&p).expect("read file"));
        }
    }
}

#[test]
fn every_used_tabler_icon_is_in_the_subset() {
    let root = env!("CARGO_MANIFEST_DIR");
    let token = Regex::new(r"ti-[a-z0-9-]+").unwrap();
    let rule = Regex::new(r"\.(ti-[a-z0-9-]+):before").unwrap();

    // Real Tabler icons (the full source) and the shipped subset.
    let full = fs::read_to_string(format!("{root}/assets/icons/tabler-icons-full.css"))
        .expect("read full tabler css");
    let real: HashSet<&str> = rule
        .captures_iter(&full)
        .map(|c| c.get(1).unwrap().as_str())
        .collect();
    let shipped = fs::read_to_string(format!("{root}/assets/icons/tabler-icons.min.css"))
        .expect("read shipped tabler css");
    let shipped_set: HashSet<&str> = rule
        .captures_iter(&shipped)
        .map(|c| c.get(1).unwrap().as_str())
        .collect();

    // Every `ti-*` token referenced in templates + Rust source.
    let mut sources = Vec::new();
    read_recursive(Path::new(&format!("{root}/templates")), "html", &mut sources);
    read_recursive(Path::new(&format!("{root}/src")), "rs", &mut sources);

    // A used token that's a REAL icon must be in the shipped subset.
    // (A stray match inside a word like "multi-host" → "ti-host" isn't a
    // real icon, so it's ignored.)
    let mut missing: Vec<&str> = sources
        .iter()
        .flat_map(|s| token.find_iter(s).map(|m| m.as_str()))
        .filter(|t| real.contains(t) && !shipped_set.contains(t))
        .collect();
    missing.sort_unstable();
    missing.dedup();

    assert!(
        missing.is_empty(),
        "Tabler icons are used but missing from the shipped subset — \
         re-run `scripts/subset-tabler-icons.py`: {missing:?}"
    );
}
